package org.apache.cxf.hello_world_soap_http;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.apache.cxf.annotations.Policies;
import org.apache.cxf.annotations.Policy;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-11-01T08:04:48.499+01:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://cxf.apache.org/hello_world_soap_http", name = "Greeter")
@XmlSeeAlso({org.apache.cxf.hello_world_soap_http.types.ObjectFactory.class})
@Policies({ @Policy(uri = "ut.policy") })
public interface Greeter {

    @WebResult(name = "responseType", targetNamespace = "http://cxf.apache.org/hello_world_soap_http/types")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://cxf.apache.org/hello_world_soap_http/types", className = "org.apache.cxf.hello_world_soap_http.types.SayHi")
    @WebMethod
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://cxf.apache.org/hello_world_soap_http/types", className = "org.apache.cxf.hello_world_soap_http.types.SayHiResponse")
    public java.lang.String sayHi();

    @WebResult(name = "responseType", targetNamespace = "http://cxf.apache.org/hello_world_soap_http/types")
    @RequestWrapper(localName = "greetMe", targetNamespace = "http://cxf.apache.org/hello_world_soap_http/types", className = "org.apache.cxf.hello_world_soap_http.types.GreetMe")
    @WebMethod
    @ResponseWrapper(localName = "greetMeResponse", targetNamespace = "http://cxf.apache.org/hello_world_soap_http/types", className = "org.apache.cxf.hello_world_soap_http.types.GreetMeResponse")
    public java.lang.String greetMe(
        @WebParam(name = "requestType", targetNamespace = "http://cxf.apache.org/hello_world_soap_http/types")
        java.lang.String requestType
    );

    @Oneway
    @RequestWrapper(localName = "greetMeOneWay", targetNamespace = "http://cxf.apache.org/hello_world_soap_http/types", className = "org.apache.cxf.hello_world_soap_http.types.GreetMeOneWay")
    @WebMethod
    public void greetMeOneWay(
        @WebParam(name = "requestType", targetNamespace = "http://cxf.apache.org/hello_world_soap_http/types")
        java.lang.String requestType
    );
}
