
package org.dpytel.jaxws.jaxws_java_first_jboss;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyWebService", targetNamespace = "http://jaxws_java_first_jboss.jaxws.dpytel.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyWebService {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://jaxws_java_first_jboss.jaxws.dpytel.org/", className = "org.dpytel.jaxws.jaxws_java_first_jboss.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://jaxws_java_first_jboss.jaxws.dpytel.org/", className = "org.dpytel.jaxws.jaxws_java_first_jboss.HelloResponse")
    public String hello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
